## Mengingat NumPy

In [1]:
import numpy as np
np_tinggi = np.array([1.73, 1.68, 1.71, 1.89, 1.79]) #m
np_berat = np.array([65.4, 59.2, 63.6, 88.4, 68.7]) #kg
bmi = np_berat / np_tinggi ** 2


In [2]:
bmi

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

In [3]:
bmi > 23

array([False, False, False,  True, False])

In [4]:
bmi[bmi>23]

array([24.7473475])

## Komparasi Numerik

In [5]:
2 < 3 

True

In [6]:
2 == 3

False

In [7]:
2 <= 3

True

In [10]:
3 <= 3

True

In [11]:
x = 2

In [12]:
y = 3

In [14]:
x >= y

False

## Komparasi yang lain

In [16]:
'dian' > 'diantemi'

False

In [ ]:
3 < 'dian' #tidak bisa 

TypeError: ignored

In [17]:
3 < 4.1

True

In [18]:
bmi

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

In [ ]:
bmi > 23

array([False, False, False,  True, False])

In [ ]:
# < 
# <= 
# > 
# >= 
# == 
# !=

## Boolean Operator

In [ ]:
# and, or, not

In [ ]:
True and True

True

In [ ]:
False and True

False

In [ ]:
True and False

False

In [ ]:
False and False

False

In [ ]:
x = 12

In [ ]:
x > 5 and x < 15

True

In [ ]:
True or True

True

In [ ]:
False or True

True

In [ ]:
True or False

True

In [ ]:
False or False

False

In [ ]:
y = 5

In [ ]:
y < 7 or y > 13

True

In [ ]:
not True

False

In [ ]:
not False

True

## Kembali ke NumPy

In [ ]:
bmi

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

In [ ]:
bmi > 21

array([ True, False,  True,  True,  True])

In [ ]:
bmi < 22

array([ True,  True,  True, False,  True])

In [ ]:
bmi > 21 and bmi <22 #akan error karena memunculkan perintah ambigu

ValueError: ignored

In [22]:
 np.logical_or(bmi > 21, bmi < 22) #np.logical_and np.logical_or np.logical_or #saran pakai np (numpy)

array([ True,  True,  True,  True,  True])

In [23]:
np.logical_and(bmi>21,bmi<22)

array([ True, False,  True, False,  True])

In [24]:
bmi[np.logical_and(bmi>21,bmi<22)] #based on intersection/irisan

array([21.85171573, 21.75028214, 21.44127836])

In [21]:
bmi[np.logical_or(bmi > 21, bmi < 22)] #gabungan

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

## if, elif, else (conditional statement)

In [27]:
z = 7
if z % 2 == 0 :
    print("z adalah genap")
else :
    print("z adalah ganjil")

z adalah ganjil


In [ ]:
z = 4
if z % 2 == 0:
    print("Mengecek " + str(z))
    print("z adalah genap")

Mengecek 4
z adalah genap


In [ ]:
z = 5 # TIDAK TEREKSEKUSI KARENA FALSE
if z % 2 == 0:
    print("Mengecek " + str(z))
    print("z adalah genap")

In [ ]:
z = 5
if z % 2 == 0 :
    print("z adalah genap")
else :
    print("z adalah ganjil")

z adalah ganjil


In [29]:
z = 11
if z % 2 == 0:
    print("z habis dibagi 2")
elif z % 3 == 0:
    print("z habis dibagi 3")
else :
    print("z tidak habis dibagi 2 maupun 3")

z tidak habis dibagi 2 maupun 3


In [ ]:
z = 6
if z % 2 == 0:
    print("z habis dibagi 2")
elif z % 3 == 0:
    print("z habis dibagi 3")
else :
    print("z tidak habis dibagi 2 maupun 3")

z habis dibagi 2


## Filtering pandas

In [31]:
#access from drive
#access data o link gdrive
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [32]:
import os
os.listdir('/content/gdrive/My Drive/DSC-UTM/Bagian-2-Python-Lanjutan/')
path_data = ('/content/gdrive/My Drive/DSC-UTM/Bagian-2-Python-Lanjutan/')

In [33]:
import pandas as pd
df = pd.read_csv(path_data+'negara.csv', index_col=0)
df

country    capital    area  population
BR        Brazil   Brasilia   8.516      200.40
RU        Russia     Moscow  17.100      143.50
IN         India  New Delhi   3.286     1252.00
CH         China    Beijing   9.597     1357.00
SA  South Africa   Pretoria   1.221       52.98

- Tujuan: Mencari Negara dengan dengan luas diatas 8 juta km^2

In [ ]:
df['area'] #  alternatif df.loc[:,"area"] atau df.iloc[:,2]

BR     8.516
RU    17.100
IN     3.286
CH     9.597
SA     1.221
Name: area, dtype: float64

In [ ]:
df['area'] > 8

BR     True
RU     True
IN    False
CH     True
SA    False
Name: area, dtype: bool

In [34]:
#fiter data dengan area >8
area_8 = df[df['area']>8]

In [35]:
area_8

country   capital    area  population
BR  Brazil  Brasilia   8.516       200.4
RU  Russia    Moscow  17.100       143.5
CH   China   Beijing   9.597      1357.0

## Menggunakan Boolean Operator

In [37]:
import numpy as np

In [ ]:
np.logical_and(df["area"] > 8, df["area"] < 10)

BR     True
RU    False
IN    False
CH     True
SA    False
Name: area, dtype: bool

In [38]:
df[np.logical_and(df["area"] > 8, df["area"] < 10)]

country   capital   area  population
BR  Brazil  Brasilia  8.516       200.4
CH   China   Beijing  9.597      1357.0

###  negara mana dengan populasi lebih dari 1000 dan area lebih dari 3.5?

In [39]:
df[np.logical_and(df["population"]>1000,df["area"]>3.5)]

country  capital   area  population
CH   China  Beijing  9.597      1357.0

### Carilah kepadatan populasi(population density) dan temukan 3 negara kepadatan >100
$density$ = $\frac{population}{area}$



In [40]:
df['density'] = df['population']/df['area']
df

country    capital    area  population     density
BR        Brazil   Brasilia   8.516      200.40   23.532175
RU        Russia     Moscow  17.100      143.50    8.391813
IN         India  New Delhi   3.286     1252.00  381.010347
CH         China    Beijing   9.597     1357.00  141.398354
SA  South Africa   Pretoria   1.221       52.98   43.390663

In [41]:
df['country'][df['density']>100]

IN    India
CH    China
Name: country, dtype: object